### PR TITLE
Greatly reduce scope of dirty flag

### PR DESCRIPTION
**Pull request by athre0z**
This PR greatly reduces the scope of the dirty flag, from previously wrapping around the whole select/insert method to now only protect atomic sending/reading of single packets.

I was hoping to be able to eliminate it completely, however this proved to be not possible with the current design because inserts of multiple blocks from an iterator can cause an exception after the opcode of the packet has already been sent out (e.g. because a block has bad types in it), making the server wait for the rest of the packet. I don't think there is any easy way to recover from a half-sent packet, so the dirty flag remains for these cases. A different approach would be to either check all failure conditions up front (resulting in pretty much duplication of most logic) or writing the data into a memory buffer first before sending it, resulting in an unnecessary copy of the data.

In any case, this now allows errors in all selects, all execute statements and all inserts where just a bad table name was specified to fail gracefully without leaving the socket dirty, which, I think, should already cover about 90% of common failure cases.

### CODE REVIEW

**Review by waralex — APPROVED** [review]
Thanks! Much better now. It seems to me that buffering the block when sending it makes sense, but it requires separate consideration not in this PR. I'll take a closer look at how it works in the official client.

**Comment by waralex** [comment]
Do you think we've improved the client enough to release a new minor version? :)

**Comment by athre0z** [comment]
Yes -- definitely enough for even a major update. Since we made breaking changes to `Date` handling, I think bumping the major version is the best thing to do to make users aware of this. This is in line with semantic versioning guidelines.

However, I found a bug / unsupported type related to DateTime's with timezones that I'd like to fix before we do that, I'll look into this now.

**Comment by waralex** [comment]
>However, I found a bug / unsupported type related to DateTime's with timezones that I'd like to fix before we do that, I'll look into this now.

Do You mean `DateTime(timestamp)` and `DateTime64(precision, timestamp)`?

>Not sure if you're familiar with this scheme.

I really didn't know that, thanks

**Comment by waralex** [comment]
Okay, thanks. Will wait :)

**Pull request merged**
